config/routes.rb
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :sessions, controller: 'users/sessions'

  mount Resque::Server.new, at: "/resque"

  get '/browse/:list_id' => 'browse', as: :browse, action: 'list'
  get '/explore' => 'welcome#home'
  get '/about' => 'pages#about', as: :about
  get "/tombstone/*id" => "pages#tombstone", as: "tombstone_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT

  get '/catalog/random' => 'catalog#random'
  get '/catalog/get_random_item' => 'catalog#random', defaults: { per_page: 1 }
  get '/catalog/:id/mods' => 'catalog#mods', as: :item_mods
  get '/catalog/:id/citation/:type' => 'catalog#show_citation', as: :item_citation

  get '/data/flare' => 'catalog#get_pivot_facet_data', as: :flare_data

  get 'carnegie/centennial_exhibition' => 'carnegie#centennial_exhibition', as: :carnegie_centennial_exhibition
  get 'carnegie/map_search' => 'carnegie#map_search', as: :carnegie_map_search

  get 'durst/map_search' => 'durst#map_search', as: :durst_map_search
  get 'durst/help' => 'durst#help', as: :durst_help
  get 'durst/favorites' => 'durst#favorites', as: :durst_favorites
  get 'durst/about_the_collection' => 'durst#about_the_collection', as: :durst_about_the_collection
  get 'durst/about_the_project' => 'durst#about_the_project', as: :durst_about_the_project
  get 'durst/acknowledgements' => 'durst#acknowledgements', as: :durst_acknowledgements
  get 'durst/old_york_library_collection_categories' => 'durst#old_york_library_collection_categories', as: :durst_old_york_library_collection_categories

  get 'ifp/partner/:key' => 'ifp#partner', as: :ifp_partner
  get 'restricted/ifp/partner/:key' => 'restricted/ifp#partner', as: :restricted_ifp_partner
  get 'ifp/about/about_the_ifp' => 'ifp#about_the_ifp', as: :ifp_about_the_ifp
  get 'ifp/about/about_the_collection' => 'ifp#about_the_collection', as: :ifp_the_collection

  get 'lcaaj/about' => 'lcaaj#about', as: :lcaaj_about
  get 'lcaaj/map_search' => 'lcaaj#map_search', as: :lcaaj_map_search

  get 'nyre/about' => 'nyre#about', as: :nyre_about
  get 'nyre/about-collection' => 'nyre#aboutcollection', as: :nyre_aboutcollection
  get 'nyre/map_search' => 'nyre#map_search', as: :nyre_map_search
  get 'nyre/projects/:id' => 'nyre/projects#show', as: :nyre_project, constraints: { id: /(\d+)|([A-Z]{2,3}\.\d{3,4}\.[A-Z]+)/ }

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  concern :publishable, Dcv::Routes::Publication.new
  concern :legacy_findable, Dcv::Routes::LegacyIds.new
  concern :previewable, Dcv::Routes::Previews.new
  concern :tree_browsable, Dcv::Routes::NodeProxies.new
  concern :search_compatibility, Dcv::Routes::SearchCompatibility.new
  concern :synchronizable, Dcv::Routes::Synchronizer.new

  concern :site_searchable, Dcv::Routes::SiteSearchable.new
  concern :site_showable, Dcv::Routes::SiteShowable.new

  subsite_concerns = [:publishable, :legacy_findable, :previewable, :tree_browsable, :search_compatibility, :synchronizable]

  repositories = %w(NNC-A NNC-EA NNC-RB NyNyCAP NyNyCBL NyNyCMA)

  repositories_constraint = lambda { |req| repositories.include?(req.params[:id]) || repositories.include?(req.params[:repository_id]) }
  resources :repositories, path: '', constraints: repositories_constraint, shallow: true, only: [:show] do
    get 'reading-room', as: 'reading_room', action: 'reading_room'
    scope module: :repositories do
      resource 'search', only: [:show], controller: 'catalog' do
        all_concerns = [:searchable] + subsite_concerns
        concerns *all_concerns
      end
      get ':id' => 'catalog#show', as: 'catalog_show', constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
      get '*id' => 'catalog#show', as: 'catalog_show_doi', constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    end
  end

  subsite_keys = (SUBSITES['public'].keys - ['uri']).map(&:to_sym)
  subsite_keys.each do |subsite_key|
    subsite_config = SUBSITES['public'][subsite_key.to_s]
    next unless subsite_config
    if subsite_config['nested'].present?
      namespace subsite_key do
        nested_keys = subsite_config['nested'].keys.map(&:to_sym)
        nested_keys.each do |nested_key|
          resource nested_key, only: [:show], controller: nested_key do
            all_concerns = [:searchable] + subsite_concerns
            concerns *all_concerns
          end
          get "#{nested_key}/:id" => "#{nested_key}#show", as: "#{nested_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
          get "#{nested_key}/*id" => "#{nested_key}#show", as: "#{nested_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
          get nested_key, to: "#{nested_key}#home", as: "#{nested_key}_home"
        end
      end
    end
    resource subsite_key, only: [:show], controller: subsite_key do
      all_concerns = [:searchable] + subsite_concerns
      concerns *all_concerns
    end
    get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
    get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
    get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
  end

  get '/restricted' => 'home#restricted', as: :restricted
  get '/restricted/projects', to: redirect('/restricted')

  SITE_SLUG_CONSTRAINT ||= lambda { |req| (['images', 'stylesheets', 'javascripts'] & [req.params[:site_slug], req.params[:site_slug]]).blank? }

  if SUBSITES['restricted'].present?
    namespace "restricted" do
      subsite_keys = (SUBSITES['restricted'].keys - ['uri']).map(&:to_sym)
      subsite_keys.each do |subsite_key|
        resource subsite_key, only: [:show], controller: subsite_key do
          all_concerns = [:searchable] + subsite_concerns
          concerns *all_concerns
        end
        get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
        get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
        get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
        get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
      end
      get "sites" => "sites#index"
      get '/:slug', controller: 'sites', action: 'home', as: 'site'
      resources 'sites', only: [:edit, :update], param: :slug, path: '', constraints: SITE_SLUG_CONSTRAINT do
        scope module: :sites do
          resource 'permissions', only: [:edit, :show, :update], controller: 'permissions'
          resource 'scope_filters', only: [:edit, :show, :update], controller: 'scope_filters'
          resource 'search_configuration', only: [:edit, :show, :update], controller: 'search_configuration'
          resource 'search', only: [:show], controller: 'search' do
            concerns :site_searchable
          end
          get 'map_search', controller: 'search'
          concerns :site_showable
          resources 'pages', except: [:index, :create, :new], param: :slug, path: '', constraints: lambda { |req| !['edit', 'pages'].include?(req.params[:slug]) }
          resources 'pages', only: [:index, :create, :new], param: :slug
        end
      end
      get "sites/:slug", to: redirect("/%{slug}")
    end
  end

  namespace  :iiif do
    scope ':version', version: /[23]/, registrant: /10\.[^\/]+/, doi: /[^\/]+/,
      collection_registrant: /10\.[^\/]+/, collection_doi: /[^\/]+/,
      manifest_registrant: /10\.[^\/]+/, manifest_doi: /[^\/]+/,
      defaults: { version: 3 } do
      get '/login', to: 'access#login', as: :login
      defaults format: 'json' do
        get '/kiosk', to: 'access#kiosk', as: :kiosk
        get '/presentation/:manifest_registrant/:manifest_doi', to: 'presentations#show', as: :presentation
        get '/presentation/:collection_registrant/:collection_doi/collection(/*proxy_path)', to: 'presentations#proxy_collection', as: :proxy_collection, constraints: { format: 'json' }
        get '/presentation/:collection_registrant/:collection_doi/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :proxy_collected_manifest, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/collection', to: 'presentations#aspace_collection', as: :aspace_collection, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :aspace_collected_manifest, constraints: { format: 'json' }
        get '/presentation/:manifest_registrant/:manifest_doi/manifest', to: 'presentations#manifest', as: :manifest
        get '/presentation/:manifest_registrant/:manifest_doi/canvas/:registrant/:doi', to: 'presentations#canvas', as: :canvas
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/probe', to: 'presentations#probe', as: :probe
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/:id', to: 'presentations#annotation', as: :annotation
        get '/presentation/:manifest_registrant/:manifest_doi/annotationPage/:registrant/:doi', to: 'presentations#annotation_page', as: :annotation_page
      end
    end
  end

  namespace :resolve do
    scope ':registrant', registrant: /10\.[A-Za-z0-9\-]+/, doi: /[^\/]+/ do
      defaults format: 'json' do

app/helpers/field_display_helpers/repository.rb
module FieldDisplayHelpers::Repository
  def field_helper_repo_code_value(args = {})
    document = args.fetch(:document, {}).to_h.with_indifferent_access
    return unless document.present?
    document['repo_code_lookup'] ||= begin
      repo_code = document['lib_repo_code_ssim']&.first
      repo_fields = ['lib_repo_full_ssim', 'lib_repo_short_ssim']
      repo_fields.detect do |field|
        unless document[field].blank?
          codes = code_map_for_repo_field(field)
          document[field].detect do |repo_value|
            repo_code ||= codes[repo_value]
          end
        end
      end
      repo_code
    end
  end

  def generate_finding_aid_url(bib_id, document, clio_only: false, deep_link: false)
    repo_code = field_helper_repo_code_value(document: document)
    repo_slug = t("cul.archives.arclight_slug.#{repo_code.downcase.sub('-', '')}") if repo_code
    if repo_slug.present? && bib_id && !clio_only
      finding_aid_url = "https://findingaids.library.columbia.edu/archives/cul-#{bib_id}"
      if deep_link && document[FieldDisplayHelpers::ASPACE_PARENT_FIELD].present?
        return "#{finding_aid_url}_aspace_#{Array(document[FieldDisplayHelpers::ASPACE_PARENT_FIELD]).first}"
      end
      finding_aid_url
    else
      "https://clio.columbia.edu/catalog/#{bib_id}" if bib_id
    end
  end

  # Link to a translated lib_repo_short_ssim value
  # as a library location URL, if available
  def link_to_repo_homepage(repo_value, code=false)
    url = code ? ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.url.repo'))[repo_value] : get_short_repo_names_to_urls[repo_value]
    return unless url
    label = code ? ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.full.repo'))[repo_value] : get_short_repo_names_to_full_repo_names.fetch(repo_value, repo_value)
    link_to(label, url)
  end

  def show_field_repository_to_facet_link(args)

    facet_field_name = :lib_repo_short_ssim
    full_repo_names_to_short_repo_names = get_full_repo_names_to_short_repo_names()

    display_values = args[:document][args[:field]]

    display_values.map {|display_value|
      facet_value = display_value # by default
      if full_repo_names_to_short_repo_names.has_key?(display_value)
        facet_value = full_repo_names_to_short_repo_names[display_value]
      end

      url_for_facet_search = search_action_path(:f => {facet_field_name => [facet_value]}) if blacklight_config.show_fields[args[:field]].link_to_facet

      if display_value == 'Non-Columbia Location' && args[:document]['lib_repo_text_ssm'].present?
        result_src = [args[:document]['lib_repo_text_ssm'].first]
        result_src << link_to("(#{display_value})", url_for_facet_search) if url_for_facet_search
      else
        repo_code = field_helper_repo_code_value(args)
        result_src = [link_to_repo_homepage(repo_code, true)]
        result_src << "<em>#{link_to("Browse Location’s Digital Content", url_for_facet_search)}</em>"  if url_for_facet_search
      end
      result_src.compact.join('<br />').html_safe
    }
  end

  def show_repository_to_web_link(args)

    facet_field_name = args[:field]
    codes_lookup = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.' + facet_field_name.split('_')[-2] + '.repo').invert)

    repo_names = args[:document][args[:field]]

    repo_names.map do |repo_name|
      if codes_lookup.has_key?(repo_name)
        code = codes_lookup[repo_name]
        web_url = I18n.t("ldpd.url.repo.#{code}") if code
      end

      if web_url
        link_to(repo_name, web_url, target: "_new")
      else
        repo_name
      end
    end
  end

  def show_translated_repository_label(args)
    values = args[:document][args[:field]]
    repo_codes = args[:document]['lib_repo_code_ssim']
    if repo_codes
      values = repo_codes.map { |repo_code| repository_display_value(repo_code) }
    end
    field_config = (controller.action_name.to_sym == :index) ?
      blacklight_config.index_fields[args[:field]] :
      blacklight_config.show_fields[args[:field]]
    separator = field_config[:separator] || '; '
    Array(values).compact.join(separator)
  end

  def show_repository_location_with_contact(args)
    repo_code = field_helper_repo_code_value(args)
    repo_display = repository_display_value(repo_code)
    return unless repo_display
    email_display = repository_email_contact(repo_code)
    if args[:mixed_content]
      message = "Additional content may be accessible in the reading room of the #{repo_display}. Please make arrangements in advance of your visit."
    else
      message = "This item is accessible in the reading room of the #{repo_display}. Please make arrangements in advance of your visit."
    end
    if email_display
      message << " Contact #{link_to(email_display, "mailto:#{email_display}")}."
    end
    message.html_safe
  end

  def code_map_for_repo_field(field)
    ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.' + field.split('_')[-2] + '.repo').invert)
  end

  def get_short_repo_names_to_full_repo_names
    short_repo_names_to_marc_codes = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.short.repo').invert)
    marc_codes_to_full_repo_names = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.full.repo'))

    new_hash = {}

    short_repo_names_to_marc_codes.each {|key, value|
      new_hash[key] = marc_codes_to_full_repo_names[value]
    }

    return new_hash
  end

  def get_short_repo_names_to_urls
    short_repo_names_to_marc_codes = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.short.repo').invert)
    marc_codes_to_urls = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.url.repo'))

    new_hash = {}

    short_repo_names_to_marc_codes.each {|key, value|
      new_hash[key] = marc_codes_to_urls[value]
    }

    return new_hash
  end

  def get_full_repo_names_to_short_repo_names
    full_repo_names_to_marc_codes = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.full.repo').invert)
    marc_codes_to_short_repo_names = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.short.repo'))

    new_hash = {}

    full_repo_names_to_marc_codes.each {|key, value|
      new_hash[key] = marc_codes_to_short_repo_names[value]
    }

    return new_hash
  end

  def get_long_repo_names_to_short_repo_names
    full_repo_names_to_marc_codes = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.long.repo').invert)
    marc_codes_to_short_repo_names = ActiveSupport::HashWithIndifferentAccess.new(I18n.t('ldpd.short.repo'))

    new_hash = {}

    full_repo_names_to_marc_codes.each {|key, value|
      new_hash[key] = marc_codes_to_short_repo_names[value]
    }

    return new_hash
  end
end

app/views/repositories/_archives_search_form.html.erb
<%= form_tag 'https://findingaids.library.columbia.edu/archives', :method => :get, :class => ['clearfix', 'flex-fill'] do %>
  <div class="input-group">
    <label for="archives_q" class="sr-only"><%= t('blacklight.search.form.q') %></label>
    <%= text_field_tag :q, params[:q], :placeholder => (!query_has_constraints? ?  t(:"dlc.search_placeholder.new.archives", default: :'dlc.search_placeholder.new.default').html_safe : t(:"dlc.search_placeholder.modified.#{controller.controller_name}", default: :'dlc.search_placeholder.modifed.default').html_safe), :class => "search_q q form-control", :id => "archives_q" %>
    <input type="hidden" name="f[repository][]" value="<%= t("cul.archives.arclight_slug.#{params[:repository_id].downcase.sub('-','')}") %>" />
    <input type="hidden" name="group" value="true" />
    <div class="input-group-append">
      <button class="btn btn-primary search-btn" type="submit" aria-label="Submit">
        <span class="fa fa-search"></span>
      </button>
    </div>
  </div>
<% end %>

app/views/repositories/_header_navbar.html.erb
<%
repository_key = params[:repository_id] || params[:site_slug] || controller.subsite_key
%>
<% if repository_key && (current_page?(repository_url(repository_key)) or current_page?(repository_reading_room_url(repository_id: repository_key))) %>
	<nav class="navbar navbar-expand d-flex flex-column" id="site-banner">
		<h1>Columbia University Libraries Digital Collections</h1>
		<h2><%= repository_physical_location(repository_key) %></h2>
	</nav>
<% elsif repository_key %>
	<nav class="navbar navbar-expand d-flex flex-md-row flex-sm-column" id="site-banner">
		<a href="<%= repository_path(repository_key) %>" id="site-title" class="navbar-brand text-lg-left"><%= repository_physical_location(repository_key) %></a>
		<%= render Dcv::SearchBar::RepositoriesComponent.new(
			url: search_repository_search_path(repository_id: repository_key),
			advanced_search_url: search_repository_search_path(repository_id: repository_key, action: 'advanced_search'),
			params: search_state.params_for_search.except(:qt),
			autocomplete_path: search_action_path(action: :suggest),
			content_availability: 'onsite'
		) if repository_key -%>
	</nav>
<% end %><%= render("secondary_nav") if repository_key %>
<% if controller.reading_room_client? -%>
	<div class="note">This workstation provides access to content that can only be viewed on-site in the reading room.</div>
<% end -%>

app/views/repositories/_search_form.html.erb
<% availability ||= false # do not require to be passed as a local -%>
<% search_action_url = search_repository_catalog_path(repository_id: params[:repository_id]) -%>
<%= form_tag search_action_url, :method => :get, :class => ['clearfix', 'flex-fill'] do %>
  <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :repository_id, :qt, :page, :utf8, :format).tap { |p| p[:'f[content_availability][]'] = availability if availability; p }) %>

  <div class="input-group flex-fill">
    <% unless search_fields.empty? %>
    <span class="input-group-prepend hidden"> <%# to be removed. might need hidde %>
      <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
      <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search_field") %>
      <span class="sr-only"><%= t('blacklight.search.form.search_field.post_label') %></span>
    </span>
    <% end %>
    <label for="q" class="sr-only"><%= t('blacklight.search.form.q') %></label>
    <%= text_field_tag :q, params[:q], :placeholder => (!query_has_constraints? ?  t(:"dlc.search_placeholder.new.#{controller.controller_name}", default: :'dlc.search_placeholder.new.default').html_safe : t(:"dlc.search_placeholder.modified.#{controller.controller_name}", default: :'dlc.search_placeholder.modifed.default').html_safe), :class => "search_q q form-control", :id => "q" %>
    <div class="input-group-append">
  <%= link_to '<i class="fa fa-remove"></i>'.html_safe, start_over_path, :title => 'Start Over', :class => 'btn btn-secondary reset-btn' if query_has_constraints? %>
      <button class="btn btn-primary search-btn" type="submit" aria-label="Submit">
        <span class="fa fa-search"></span>
      </button>
    </div>
  </div>

<% end %>

app/views/repositories/_secondary_nav.html.erb
<nav id="secondary-nav" class="navbar d-flex px-0">
	<%- cache @subsite do -%>
		<ul class="nav nav-pills mr-auto">
			<li class="nav-item">
				<a href="<%= repository_reading_room_url(repository_id: @subsite.repository_id) %>" class="nav-link" title="Online Reading Room Home"><i class="fa fa-home"></i></a>
			</li>
			<%- @subsite.nav_menus.each do |nav_menu| -%>
				<%- if nav_menu.length > 1 -%>
					<li class="dropdown">
						<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%=nav_menu.label %> <b class="caret"></b></a>
						<ul class="dropdown-menu list-unstyled dropdown-menu-left">
							<%- nav_menu.links.each do |nav_link| -%>
								<li><%= link_to_nav(nav_link, link_class: "dropdown-item", site_slug: params[:repository_id]) %></li>
							<%- end -%>
						</ul>
					</li>
				<%- else -%>
					<li class="nav-item"><%= link_to_nav(nav_menu.links[-1]) %></li>
				<%- end -%>
			<%- end -%>
		</ul>
	<%- end -%>
	<%- if map_search_settings_for_subsite.present? -%>
		<ul class="nav nav-pills">
			<li class="nav-item"><a href="<%= '/' + @subsite.slug + '/map_search' %>" class="nav-link mx-auto px-md-1"><span class="fa fa-map-marker"></span> Map<span class="d-md-none d-lg-inline"> All Items</span></a></li>
		</ul>
	<%- end -%>
	<ul class="nav nav-pills">
		<li class="nav-item">
			<a href="/restricted" class="nav-link" title="List Online Reading Rooms"><i class="fa fa-list-alt"></i></a>
		</li>
	</ul>
</nav>

app/views/repositories/page.html.erb
<%- cache [@subsite, @page] do -%>
<div id="content" class="row mx-auto">
    <h2 class="text-center w-100"><%= @page.title %></h2>
    <%= render Dcv::PageImageComponent.new(depictable: @page, blacklight_config: @subsite.blacklight_config) %>
    <hr class="w-100">
    <%- @page.site_text_blocks.sort { |a,b| a.sort_label <=> b.sort_label }.each do |text_block| -%>
        <div class="inner">
            <%- if text_block.label.present? -%>
                <h3 class="text-center"><%= text_block.label %></h3>
            <%- end -%>
            <%= render Dcv::PageImageComponent.new(depictable: text_block, blacklight_config: @subsite.blacklight_config) %>
            <%= controller.render_markdown(text_block.markdown) %>
        </div>
    <%- end -%>
</div>
<%- end -%>

app/views/repositories/reading_room.html.erb
<%-
digital_projects = controller.digital_projects
%>
<div id="portals" class="row">
  <div class="card w-100 mb-2">
    <div class="card-body">
      <h3 class="card-title">Archival Collections Portal</h3>
      <%= render "archives_search_form" %>
    </div>
      <div class="card-footer">View archival finding aids that include links to both open and restricted digital content.</div>
  </div>
  <div class="card w-100 mb-2">
    <div class="card-body">
      <h3 class="card-title">Digital Collections</h3>
      <%= render Dcv::SearchBar::RepositoriesComponent.new(
        url: search_repository_search_path(repository_id: params[:repository_id]),
        advanced_search_url: search_repository_search_path(repository_id: params[:repository_id], action: 'advanced_search'),
        params: search_state.params_for_search.except(:qt),
        autocomplete_path: search_action_path(action: :suggest),
        content_availability: 'onsite'
        ) -%>
    </div>
    <div class="card-footer">Search digital content available in the <%= I18n.t("ldpd.short.repo.#{params[:repository_id]}") %> reading room<%= ', or navigate via the links below' if digital_projects.present? -%>.</div>
  </div>
</div>
<%= render template: 'reading_room/projects_and_exhibitions' %>