config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root :to => "catalog#home"

  devise_for :users, skip: [:sessions], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :sessions, controller: 'users/sessions'

  mount Resque::Server.new, at: "/resque"

  get '/browse/:list_id' => 'browse', as: :browse, action: 'list'
  get '/explore' => 'welcome#home'
  get '/about' => 'pages#about', as: :about
  get "/tombstone/*id" => "pages#tombstone", as: "tombstone_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT

  get '/catalog/random' => 'catalog#random'
  get '/catalog/get_random_item' => 'catalog#random', defaults: { per_page: 1 }
  get '/catalog/:id/mods' => 'catalog#mods', as: :item_mods
  get '/catalog/:id/citation/:type' => 'catalog#show_citation', as: :item_citation

  get '/data/flare' => 'catalog#get_pivot_facet_data', as: :flare_data

  get 'carnegie/centennial_exhibition' => 'carnegie#centennial_exhibition', as: :carnegie_centennial_exhibition
  get 'carnegie/map_search' => 'carnegie#map_search', as: :carnegie_map_search

  get 'durst/map_search' => 'durst#map_search', as: :durst_map_search
  get 'durst/help' => 'durst#help', as: :durst_help
  get 'durst/favorites' => 'durst#favorites', as: :durst_favorites
  get 'durst/about_the_collection' => 'durst#about_the_collection', as: :durst_about_the_collection
  get 'durst/about_the_project' => 'durst#about_the_project', as: :durst_about_the_project
  get 'durst/acknowledgements' => 'durst#acknowledgements', as: :durst_acknowledgements
  get 'durst/old_york_library_collection_categories' => 'durst#old_york_library_collection_categories', as: :durst_old_york_library_collection_categories

  get 'ifp/partner/:key' => 'ifp#partner', as: :ifp_partner
  get 'restricted/ifp/partner/:key' => 'restricted/ifp#partner', as: :restricted_ifp_partner
  get 'ifp/about/about_the_ifp' => 'ifp#about_the_ifp', as: :ifp_about_the_ifp
  get 'ifp/about/about_the_collection' => 'ifp#about_the_collection', as: :ifp_the_collection

  get 'lcaaj/about' => 'lcaaj#about', as: :lcaaj_about
  get 'lcaaj/map_search' => 'lcaaj#map_search', as: :lcaaj_map_search

  get 'nyre/about' => 'nyre#about', as: :nyre_about
  get 'nyre/about-collection' => 'nyre#aboutcollection', as: :nyre_aboutcollection
  get 'nyre/map_search' => 'nyre#map_search', as: :nyre_map_search
  get 'nyre/projects/:id' => 'nyre/projects#show', as: :nyre_project, constraints: { id: /(\d+)|([A-Z]{2,3}\.\d{3,4}\.[A-Z]+)/ }

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  concern :publishable, Dcv::Routes::Publication.new
  concern :legacy_findable, Dcv::Routes::LegacyIds.new
  concern :previewable, Dcv::Routes::Previews.new
  concern :tree_browsable, Dcv::Routes::NodeProxies.new
  concern :search_compatibility, Dcv::Routes::SearchCompatibility.new
  concern :synchronizable, Dcv::Routes::Synchronizer.new

  concern :site_searchable, Dcv::Routes::SiteSearchable.new
  concern :site_showable, Dcv::Routes::SiteShowable.new

  subsite_concerns = [:publishable, :legacy_findable, :previewable, :tree_browsable, :search_compatibility, :synchronizable]

  repositories = %w(NNC-A NNC-EA NNC-RB NyNyCAP NyNyCBL NyNyCMA)

  repositories_constraint = lambda { |req| repositories.include?(req.params[:id]) || repositories.include?(req.params[:repository_id]) }
  resources :repositories, path: '', constraints: repositories_constraint, shallow: true, only: [:show] do
    get 'reading-room', as: 'reading_room', action: 'reading_room'
    scope module: :repositories do
      resource 'search', only: [:show], controller: 'catalog' do
        all_concerns = [:searchable] + subsite_concerns
        concerns *all_concerns
      end
      get ':id' => 'catalog#show', as: 'catalog_show', constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
      get '*id' => 'catalog#show', as: 'catalog_show_doi', constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    end
  end

  subsite_keys = (SUBSITES['public'].keys - ['uri']).map(&:to_sym)
  subsite_keys.each do |subsite_key|
    subsite_config = SUBSITES['public'][subsite_key.to_s]
    next unless subsite_config
    if subsite_config['nested'].present?
      namespace subsite_key do
        nested_keys = subsite_config['nested'].keys.map(&:to_sym)
        nested_keys.each do |nested_key|
          resource nested_key, only: [:show], controller: nested_key do
            all_concerns = [:searchable] + subsite_concerns
            concerns *all_concerns
          end
          get "#{nested_key}/:id" => "#{nested_key}#show", as: "#{nested_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
          get "#{nested_key}/*id" => "#{nested_key}#show", as: "#{nested_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
          get nested_key, to: "#{nested_key}#home", as: "#{nested_key}_home"
        end
      end
    end
    resource subsite_key, only: [:show], controller: subsite_key do
      all_concerns = [:searchable] + subsite_concerns
      concerns *all_concerns
    end
    get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
    get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
    get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
  end

  get '/restricted' => 'home#restricted', as: :restricted
  get '/restricted/projects', to: redirect('/restricted')

  SITE_SLUG_CONSTRAINT ||= lambda { |req| (['images', 'stylesheets', 'javascripts'] & [req.params[:site_slug], req.params[:site_slug]]).blank? }

  if SUBSITES['restricted'].present?
    namespace "restricted" do
      subsite_keys = (SUBSITES['restricted'].keys - ['uri']).map(&:to_sym)
      subsite_keys.each do |subsite_key|
        resource subsite_key, only: [:show], controller: subsite_key do
          all_concerns = [:searchable] + subsite_concerns
          concerns *all_concerns
        end
        get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
        get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
        get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
        get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
      end
      get "sites" => "sites#index"
      get '/:slug', controller: 'sites', action: 'home', as: 'site'
      resources 'sites', only: [:edit, :update], param: :slug, path: '', constraints: SITE_SLUG_CONSTRAINT do
        scope module: :sites do
          resource 'permissions', only: [:edit, :show, :update], controller: 'permissions'
          resource 'scope_filters', only: [:edit, :show, :update], controller: 'scope_filters'
          resource 'search_configuration', only: [:edit, :show, :update], controller: 'search_configuration'
          resource 'search', only: [:show], controller: 'search' do
            concerns :site_searchable
          end
          get 'map_search', controller: 'search'
          concerns :site_showable
          resources 'pages', except: [:index, :create, :new], param: :slug, path: '', constraints: lambda { |req| !['edit', 'pages'].include?(req.params[:slug]) }
          resources 'pages', only: [:index, :create, :new], param: :slug
        end
      end
      get "sites/:slug", to: redirect("/%{slug}")
    end
  end

  namespace  :iiif do
    scope ':version', version: /[23]/, registrant: /10\.[^\/]+/, doi: /[^\/]+/,
      collection_registrant: /10\.[^\/]+/, collection_doi: /[^\/]+/,
      manifest_registrant: /10\.[^\/]+/, manifest_doi: /[^\/]+/,
      defaults: { version: 3 } do
      get '/login', to: 'access#login', as: :login
      defaults format: 'json' do
        get '/kiosk', to: 'access#kiosk', as: :kiosk
        get '/presentation/:manifest_registrant/:manifest_doi', to: 'presentations#show', as: :presentation
        get '/presentation/:collection_registrant/:collection_doi/collection(/*proxy_path)', to: 'presentations#proxy_collection', as: :proxy_collection, constraints: { format: 'json' }
        get '/presentation/:collection_registrant/:collection_doi/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :proxy_collected_manifest, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/collection', to: 'presentations#aspace_collection', as: :aspace_collection, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :aspace_collected_manifest, constraints: { format: 'json' }
        get '/presentation/:manifest_registrant/:manifest_doi/manifest', to: 'presentations#manifest', as: :manifest
        get '/presentation/:manifest_registrant/:manifest_doi/canvas/:registrant/:doi', to: 'presentations#canvas', as: :canvas
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/probe', to: 'presentations#probe', as: :probe
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/:id', to: 'presentations#annotation', as: :annotation

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-

# This controller currently only answers requests for the /restricted "home" page
class HomeController < ApplicationController

  include Cul::Omniauth::AuthorizingController
  include Cul::Omniauth::RemoteIpAbility
  include Dcv::Sites::ConfiguredLayouts
  include Dcv::Sites::ReadingRooms

  before_action :authorize_action, only:[:restricted]
  before_action :store_unless_user

  layout Proc.new { |controller|
    self.subsite_layout
  }

  def subsite_config
    {'layout' => 'gallery', 'slug' => 'restricted'}
  end

  def subsite_styles
    ["#{subsite_layout}-#{Dcv::Sites::Constants.default_palette}", "catalog"]
  end

  def authorize_action
    return if current_ability.ip_to_location_uris(request.remote_ip).present?

    raise CanCan::AccessDenied unless current_user
  end
  
  def restricted
  end  
end

app/views/home/index.html.erb
<%
featured_proj = controller.digital_projects.select { |proj| proj[:facet_value].present? }.sample
%>

<div class="row">
  <div id="sidebar" class="col-md-3">
    <div class="inner">
       <div id="home-sidebar-news">
          <h6>WELCOME</h6>
            <p>The Digital Library Collections (DLC) website is a gateway to digital reproductions and descriptions of photographs, posters, drawings, objects, ephemera, and manuscripts as well as other archival material from Columbia's rare and special collections.  As of January 2016 the DLC repository includes ca. 190,000 digital objects. <a href="<%= about_url %>">More &raquo;</a></p>
            <hr>
          <h6>COLLECTION SPOTLIGHT</h6>
          <div class="collection-title"><%= featured_proj[:name] %></div>
		  <p><a href="<%= search_action_path(:f => {'lib_project_short_ssim' => [featured_proj[:facet_value]]})  %>"><img src="<%= asset_url('digital_projects_page/' + featured_proj[:image]); %>" class="thumbnail pull-right" alt="<%= featured_proj[:name] %>"></a><%= featured_proj[:description].html_safe %> <a href="<%= search_action_path(:f => {'lib_project_short_ssim' => [featured_proj[:facet_value]]})  %>" class="inline-block">View this Collection &raquo;</a></p>
          <div class="clearfix"></div>
         </div>
      </div>
      <div id="home-sidebar-about">
          <p><a href="<%= about_url %>">Learn more about the DLC &raquo;</a></p>
      </div>
  </div>

  <div id="content" class="col-md-9">
        <div id="home-page-content">

            <div id="home-page-tabs" class="inner">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#projects" data-toggle="tab">Selected Collections</a></li>
                    <% @browse_lists.each do |facet_name, data| %>
                        <li><a href="#tab_<%= facet_name %>" data-toggle="tab"><%= data['display_label'] %></a></li>
                    <% end %>
                    <li class="pull-right"><a href="#other-collections" data-toggle="tab">All Collections</a></li>
					<!--li class="pull-right non-tab"><a onclick="window.open(this.href);return false;" data-toggle="tooltip" data-placement="left" href="http://library.columbia.edu/find/digital-collections.html" title="See All Digital Collections">All Collections <i class="glyphicon glyphicon-new-window"></i></a></li-->
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fadein active" id="projects">
                        <%= render template: 'pages/projects_and_exhibitions' %>
                    </div>
                    <% if @browse_lists.present? %>
                        <% @browse_lists.each do |facet_name, data| %>
                            <%= render template: "pages/#{facet_name}", locals: {facet_name: facet_name, data: data} if data['value_pairs'].present? %>
                        <% end %>
                    <% end %>
                    <div class="tab-pane fadein" id="other-collections">
                        <%= render template: 'pages/projects_and_exhibitions', :locals => { other_projects: true } %>
                    </div>
                </div>
            </div> <!--/.inner-->
        </div>
  </div>

</div>

app/views/home/restricted.html.erb
<div class="row">
  <div id="content" class="col-md-12">
    <div id="home-page-content">
        <h2 class="text-center text-md-left h4">READING ROOM SITES</h2>
        <div id="home-page-restricted" class="inner">
          <ul class="pb-0 pl-0 list-unstyled">
              <%- current_location_uris = controller.location_uris_for_client -%>
              <%- Rails.application.config_for(:reading_rooms).sort_by { |tuple| tuple[1].fetch(:label) }.each do |tuple| -%>
                <%- _reading_room_key, location = tuple -%>
                <li>
                  <%= render Dcv::Badges::ReadingRoom.new(reading_room: location, current_location_uris: current_location_uris) %><%= link_to(location[:label], repository_reading_room_path(repository_id: location[:repository_id])) %>
                </li>
              <%- end -%>
          </ul>
        </div>
        <div class="clearfix"></div>
        <div class="inner">
          <p>A core objective of Columbia University Libraries Rare Book and Manuscript Library is is to make our archival collections accessible for research and scholarship.</p>
          <p>The library-specific pages linked here allow users to search archival finding aids and digital collection content from Columbia Libraries' individual special collections. Searching done via the "Digital Collections" search box on each repository page displays results for material that is restricted from general public access for reasons relating to copyright, license, or other terms and conditions. By default the search results are filtered to display only the restricted content, labeled as "Limit by Availability > Reading Room." This filter can also be removed in order to display publicly accessible content as well.</p>
          <p><a href="<%= about_url %>">Learn more about the DLC &raquo;</a></p>
      </div>
    </div>
  </div>
</div>