config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  root :to => "catalog#home"

  devise_for :users, skip: [:sessions], controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
  }

  devise_scope :user do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :sessions, controller: 'users/sessions'

  mount Resque::Server.new, at: "/resque"

  get '/browse/:list_id' => 'browse', as: :browse, action: 'list'
  get '/explore' => 'welcome#home'
  get '/about' => 'pages#about', as: :about
  get "/tombstone/*id" => "pages#tombstone", as: "tombstone_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT

  get '/catalog/random' => 'catalog#random'
  get '/catalog/get_random_item' => 'catalog#random', defaults: { per_page: 1 }
  get '/catalog/:id/mods' => 'catalog#mods', as: :item_mods
  get '/catalog/:id/citation/:type' => 'catalog#show_citation', as: :item_citation

  get '/data/flare' => 'catalog#get_pivot_facet_data', as: :flare_data

  get 'carnegie/centennial_exhibition' => 'carnegie#centennial_exhibition', as: :carnegie_centennial_exhibition
  get 'carnegie/map_search' => 'carnegie#map_search', as: :carnegie_map_search

  get 'durst/map_search' => 'durst#map_search', as: :durst_map_search
  get 'durst/help' => 'durst#help', as: :durst_help
  get 'durst/favorites' => 'durst#favorites', as: :durst_favorites
  get 'durst/about_the_collection' => 'durst#about_the_collection', as: :durst_about_the_collection
  get 'durst/about_the_project' => 'durst#about_the_project', as: :durst_about_the_project
  get 'durst/acknowledgements' => 'durst#acknowledgements', as: :durst_acknowledgements
  get 'durst/old_york_library_collection_categories' => 'durst#old_york_library_collection_categories', as: :durst_old_york_library_collection_categories

  get 'ifp/partner/:key' => 'ifp#partner', as: :ifp_partner
  get 'restricted/ifp/partner/:key' => 'restricted/ifp#partner', as: :restricted_ifp_partner
  get 'ifp/about/about_the_ifp' => 'ifp#about_the_ifp', as: :ifp_about_the_ifp
  get 'ifp/about/about_the_collection' => 'ifp#about_the_collection', as: :ifp_the_collection

  get 'lcaaj/about' => 'lcaaj#about', as: :lcaaj_about
  get 'lcaaj/map_search' => 'lcaaj#map_search', as: :lcaaj_map_search

  get 'nyre/about' => 'nyre#about', as: :nyre_about
  get 'nyre/about-collection' => 'nyre#aboutcollection', as: :nyre_aboutcollection
  get 'nyre/map_search' => 'nyre#map_search', as: :nyre_map_search
  get 'nyre/projects/:id' => 'nyre/projects#show', as: :nyre_project, constraints: { id: /(\d+)|([A-Z]{2,3}\.\d{3,4}\.[A-Z]+)/ }

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new

  concern :publishable, Dcv::Routes::Publication.new
  concern :legacy_findable, Dcv::Routes::LegacyIds.new
  concern :previewable, Dcv::Routes::Previews.new
  concern :tree_browsable, Dcv::Routes::NodeProxies.new
  concern :search_compatibility, Dcv::Routes::SearchCompatibility.new
  concern :synchronizable, Dcv::Routes::Synchronizer.new

  concern :site_searchable, Dcv::Routes::SiteSearchable.new
  concern :site_showable, Dcv::Routes::SiteShowable.new

  subsite_concerns = [:publishable, :legacy_findable, :previewable, :tree_browsable, :search_compatibility, :synchronizable]

  repositories = %w(NNC-A NNC-EA NNC-RB NyNyCAP NyNyCBL NyNyCMA)

  repositories_constraint = lambda { |req| repositories.include?(req.params[:id]) || repositories.include?(req.params[:repository_id]) }
  resources :repositories, path: '', constraints: repositories_constraint, shallow: true, only: [:show] do
    get 'reading-room', as: 'reading_room', action: 'reading_room'
    scope module: :repositories do
      resource 'search', only: [:show], controller: 'catalog' do
        all_concerns = [:searchable] + subsite_concerns
        concerns *all_concerns
      end
      get ':id' => 'catalog#show', as: 'catalog_show', constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
      get '*id' => 'catalog#show', as: 'catalog_show_doi', constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    end
  end

  subsite_keys = (SUBSITES['public'].keys - ['uri']).map(&:to_sym)
  subsite_keys.each do |subsite_key|
    subsite_config = SUBSITES['public'][subsite_key.to_s]
    next unless subsite_config
    if subsite_config['nested'].present?
      namespace subsite_key do
        nested_keys = subsite_config['nested'].keys.map(&:to_sym)
        nested_keys.each do |nested_key|
          resource nested_key, only: [:show], controller: nested_key do
            all_concerns = [:searchable] + subsite_concerns
            concerns *all_concerns
          end
          get "#{nested_key}/:id" => "#{nested_key}#show", as: "#{nested_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
          get "#{nested_key}/*id" => "#{nested_key}#show", as: "#{nested_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
          get nested_key, to: "#{nested_key}#home", as: "#{nested_key}_home"
        end
      end
    end
    resource subsite_key, only: [:show], controller: subsite_key do
      all_concerns = [:searchable] + subsite_concerns
      concerns *all_concerns
    end
    get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
    get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
    get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
    get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
  end

  get '/restricted' => 'home#restricted', as: :restricted
  get '/restricted/projects', to: redirect('/restricted')

  SITE_SLUG_CONSTRAINT ||= lambda { |req| (['images', 'stylesheets', 'javascripts'] & [req.params[:site_slug], req.params[:site_slug]]).blank? }

  if SUBSITES['restricted'].present?
    namespace "restricted" do
      subsite_keys = (SUBSITES['restricted'].keys - ['uri']).map(&:to_sym)
      subsite_keys.each do |subsite_key|
        resource subsite_key, only: [:show], controller: subsite_key do
          all_concerns = [:searchable] + subsite_concerns
          concerns *all_concerns
        end
        get "#{subsite_key}/:id" => "#{subsite_key}#show", as: "#{subsite_key}_show", constraints: Dcv::Routes::LEGACY_ID_CONSTRAINT
        get "#{subsite_key}/*id" => "#{subsite_key}#show", as: "#{subsite_key}_show_doi", constraints: Dcv::Routes::DOI_ID_CONSTRAINT
        get "#{subsite_key}/:slug" => "#{subsite_key}#page", as: "#{subsite_key}_page", constraints: lambda { |req| !['edit', 'pages', 'permissions', 'scope_filters', 'search_configuration'].include?(req.params[:slug]) }
        get subsite_key, to: "#{subsite_key}#home", as: "#{subsite_key}_home"
      end
      get "sites" => "sites#index"
      get '/:slug', controller: 'sites', action: 'home', as: 'site'
      resources 'sites', only: [:edit, :update], param: :slug, path: '', constraints: SITE_SLUG_CONSTRAINT do
        scope module: :sites do
          resource 'permissions', only: [:edit, :show, :update], controller: 'permissions'
          resource 'scope_filters', only: [:edit, :show, :update], controller: 'scope_filters'
          resource 'search_configuration', only: [:edit, :show, :update], controller: 'search_configuration'
          resource 'search', only: [:show], controller: 'search' do
            concerns :site_searchable
          end
          get 'map_search', controller: 'search'
          concerns :site_showable
          resources 'pages', except: [:index, :create, :new], param: :slug, path: '', constraints: lambda { |req| !['edit', 'pages'].include?(req.params[:slug]) }
          resources 'pages', only: [:index, :create, :new], param: :slug
        end
      end
      get "sites/:slug", to: redirect("/%{slug}")
    end
  end

  namespace  :iiif do
    scope ':version', version: /[23]/, registrant: /10\.[^\/]+/, doi: /[^\/]+/,
      collection_registrant: /10\.[^\/]+/, collection_doi: /[^\/]+/,
      manifest_registrant: /10\.[^\/]+/, manifest_doi: /[^\/]+/,
      defaults: { version: 3 } do
      get '/login', to: 'access#login', as: :login
      defaults format: 'json' do
        get '/kiosk', to: 'access#kiosk', as: :kiosk
        get '/presentation/:manifest_registrant/:manifest_doi', to: 'presentations#show', as: :presentation
        get '/presentation/:collection_registrant/:collection_doi/collection(/*proxy_path)', to: 'presentations#proxy_collection', as: :proxy_collection, constraints: { format: 'json' }
        get '/presentation/:collection_registrant/:collection_doi/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :proxy_collected_manifest, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/collection', to: 'presentations#aspace_collection', as: :aspace_collection, constraints: { format: 'json' }
        get '/presentation/aspace/:archives_space_id/manifest/:manifest_registrant/:manifest_doi', to: 'presentations#manifest', as: :aspace_collected_manifest, constraints: { format: 'json' }
        get '/presentation/:manifest_registrant/:manifest_doi/manifest', to: 'presentations#manifest', as: :manifest
        get '/presentation/:manifest_registrant/:manifest_doi/canvas/:registrant/:doi', to: 'presentations#canvas', as: :canvas
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/probe', to: 'presentations#probe', as: :probe
        get '/presentation/:manifest_registrant/:manifest_doi/annotation/:registrant/:doi/:id', to: 'presentations#annotation', as: :annotation

app/controllers/catalog_controller.rb
class CatalogController < SubsitesController
  include Dcv::DigitalProjectsController
  include Dcv::Catalog::BrowseListBehavior
  include Dcv::Sites::LookupController

  before_action :get_catalog_browse_lists, only: [:home, :browse]

  configure_blacklight do |config|
    Dcv::Configurators::DcvBlacklightConfigurator.configure(config)
    # Include this target's content in search results, and any additional publish targets specified in subsites.yml
    configure_blacklight_scope_constraints(config, true)
    config.add_facet_field 'content_availability', label: 'Limit by Availability', show: false,
      query: {
        onsite: { label: 'Reading Room', fq: "{!join from=cul_member_of_ssim to=fedora_pid_uri_ssi}!access_control_levels_ssim:Public*" },
        public: { label: 'Public', fq: "{!join from=cul_member_of_ssim to=fedora_pid_uri_ssi}access_control_levels_ssim:Public*" },
      }

    config.home.featured_items_component = Dcv::Catalog::ProjectListComponent
  end

  prepend_view_path('app/views/gallery')

  def search_service_context
    { builder: { addl_processor_chain: [:hide_concepts_when_query_blank_filter] } }
  end

  def subsite_layout
    'gallery'
  end

  def home_params
    {
      fq: [
        'object_state_ssi:A', # Active items only
        'active_fedora_model_ssi:Concept',
        'dc_type_sim:"Publish Target"',
        '-slug_ssim:(sites OR catalog)' # Do not include sites or catalog publish target in this list
      ],
      sort: "title_si asc, lib_date_dtsi desc",
      qt: 'search',
      rows: 250
    }
  end

  def setup_show_document
    super
    return unless @document
    scope_candidates = scope_candidates_for(@document)
    return if scope_candidates.blank?
    site_candidates = site_candidates_for(scope_candidates).where.not(id: load_subsite)
    other_sites_data = site_matches_for(@document, site_candidates)
    @document.merge_source!({ other_sites_data: other_sites_data }) if other_sites_data.present?
  end

  # get search results from the solr index forhome page
  def home
    respond_to do |format|
      format.html { render action: 'home' }
    end
  end

  def render_home_for_index?
    false
  end

  def digital_projects
    @response = search_service.repository.search(home_params)
    @document_list = @response.documents
    super
  end

  # produce a lazily-loaded list of featured items according to a supplied filter
  def featured_items(args= {})
    digital_projects
  end
end

app/controllers/concerns/dcv/catalog/alternate_home_pages.rb
module Dcv::Catalog::AlternateHomePages
  extend ActiveSupport::Concern

end

app/controllers/concerns/dcv/catalog/asset_resolver_behavior.rb
module Dcv::Catalog::AssetResolverBehavior
  extend ActiveSupport::Concern

  included do
    helper_method :identifier_to_pid
  end

  def identifier_to_pid(identifier_to_convert, pid=nil)
    @converted_ids ||= {}
    @converted_ids[identifier_to_convert] ||= pid
    @converted_ids[identifier_to_convert] ||= begin
      convertible_id = identifier_to_convert.dup # Don't want to modify the passed-in object because it might be used again outside of this method
      convertible_id.sub!(/apt\:\/columbia/,'apt://columbia') # TOTAL HACK
      convertible_id.gsub!(':','\:')
      convertible_id.gsub!('/','\/')

      p = blacklight_config.default_document_solr_params.merge(fq: "dc_identifier_ssim:\"#{convertible_id}\"")
      solr_response, resolved_list = search_results(p) { |b| b.merge(p) }
      solr_response = 
      if resolved_list.empty?
        # ba2213 thought this was a good interim until we can verify that all docs have DC:identifier set appropriately
        p[:fq] = "identifier_ssim:\"#{convertible_id}\""
        solr_response, resolved_list = search_results(p) { |b| b.merge(p) }
      end
      if resolved_list.empty?
        nil
      else
        resolved_list.first.id
      end
    end
  end
end

app/controllers/concerns/dcv/catalog/browse_list_behavior.rb
# -*- encoding : utf-8 -*-
module Dcv::Catalog::BrowseListBehavior
  extend ActiveSupport::Concern

  # Browse List Logic

  def browse_lists_cache_key
		return Dcv::LazyBrowseList::BROWSE_LISTS_KEY_PREFIX + controller_name
	end

  def get_catalog_browse_lists
    @browse_lists = Dcv::LazyBrowseList.browse_lists(controller_name)
  end
end

app/controllers/restricted/catalog_controller.rb
class Restricted::CatalogController < SubsitesController

  configure_blacklight do |config|
    Dcv::Configurators::DcvBlacklightConfigurator.configure(config)
    # Include this target's content in search results, and any additional publish targets specified in subsites.yml
    configure_blacklight_scope_constraints(config, true)
  end

  def search_service_context
    { builder: { addl_processor_chain: [:hide_concepts_when_query_blank_filter] } }
  end
end

app/helpers/catalog_helper.rb
module CatalogHelper
  include Blacklight::CatalogHelperBehavior
  include Dcv::AbilityHelperBehavior
  include Dcv::FieldSetsHelperBehavior
  include Dcv::CatalogHelperBehavior
  include Dcv::IframeHelperBehavior
  include Dcv::OreProxiesHelperBehavior
  include Dcv::StructMetadataHelperBehavior
  include Dcv::Resources::RelsIntBehavior

  def has_thumbnail? document
    true
  end

  def resources_as_list_items(document=@document, css_class)
    list_items = resources_for_document(document).collect do |doc|
      p = doc[:id].split('/')
      id = p[-1]
      c_id = p[-2]
      title = doc[:title]
      ext = doc[:mime_type].split('/')[-1].downcase
      "<li><a href=\"#{doc[:url]}\" target=\"_blank\">#{title}.#{ext} (#{doc[:width]}x#{doc[:length]})</a></li>".html_safe
    end
    list_items
  end

  def proxies(opts=params, &block)
    proxy_in = opts[:id]
    proxy_uri = "info:fedora/#{proxy_in}"
    proxy_id = opts[:proxy_id]
    proxy_in_query = "proxyIn_ssi:#{RSolr.solr_escape(proxy_uri).gsub(' ', '%20')}"
    f = [proxy_in_query]
    if proxy_id
      f << "belongsToContainer_ssi:#{RSolr.solr_escape(proxy_id).gsub(' ', '%20')}"
    else
      f << "-belongsToContainer_ssi:*"
    end
    rows = opts[:limit] || '999'
    local_params = { q: "*:*", defType: 'lucene', fq: f, rows:rows }
    _response, proxies = controller.search_service.search_results { |b| b.merge(local_params) }
    if proxies.detect {|p| p["type_ssim"] && p["type_ssim"].include?(RDF::NFO[:'#FileDataObject'])}
      if proxy_id
        query = "{!join from=proxyFor_ssi to=identifier_ssim}#{f.last}"
      else
        query = "{!join from=proxyFor_ssi to=identifier_ssim}#{proxy_in_query}"
      end
      file_members = "cul_member_of_ssim:#{RSolr.solr_escape(proxy_uri).gsub(' ', '%20')}"
      local_params = { q: query, defType: 'lucene', fq: [file_members], rows: '999' }
      _response, files = controller.search_service.search_results { |b| b.merge(local_params) }
      proxies.each do |proxy|
        file = files.detect {|f| f['identifier_ssim'].include?(proxy['proxyFor_ssi'])}
        if file
          rels_int = file.fetch('rels_int_profile_tesim',[]).first
          props = rels_int ? JSON.load(rels_int) : {}
          props = props["#{proxy_uri}/content"] || {}
          props['pid'] = file['id']
          props['extent'] ||= file['extent_ssim'] if file['extent_ssim']
          proxy.merge_source!(props)
        end
      end
    end
    if proxies.detect {|p| p["type_ssim"] && p["type_ssim"].include?(RDF::NFO[:'#Folder'])}
      query = "{!join from=id  to=belongsToContainer_ssi}#{f.join(' ')}"
      folder_counts = facets_for(query,:"facet.field" => "belongsToContainer_ssi",:"facet.limit" => '999')
      unless ( belongsToContainer = facet_to_hash(folder_counts["belongsToContainer_ssi"])).empty?
        proxies.each do |proxy|
          if proxy["type_ssim"].include?(RDF::NFO[:'#Folder']) && !proxy['extent']
            proxy.merge_source!(extent: belongsToContainer[proxy['id']])
          end
        end
      end
    end
    if block_given?
      proxies.each &block
    else
      proxies
    end
  end
end

app/views/catalog/_featured_items.html.erb
<div id="digital_projects">
	<% proj_counter = 0 %>
	<div class="row">
		<% controller.digital_projects.each do |digital_project| %>
			<% if digital_project[:browse_url].present? %>
				<div class="col-sm-3 mb-2">
					<%= render Dcv::ProjectCardComponent.new(project_data: digital_project, counter: proj_counter, additional_classes: ["h-100"]) -%>
				</div>
				<% if (proj_counter += 1) % 4 == 0 %><div class="clearfix"></div><br /><% end -%>
			<% end %>
		<% end %>
	</div>
</div>

app/views/catalog/_links_sidebar_panel.html.erb
<% configured_links ||= [] %>
<div class="inner noprint-sm">
	<ul class="list-unstyled">
		<% if configured_links.include?(:persistent) && has_persistent_link?(document) %>
			<li><%= persistent_link_to('<span class="glyphicon glyphicon-bookmark"></span> Persistent URL'.html_safe, document)  %></li>
		<% end %>
		<% if configured_links.include?(:reproduction) %>
			<li><a href="http://library.columbia.edu/services/preservation/publications_policy.html"><span class="glyphicon glyphicon-tag"></span> Order a Reproduction</a></li>
		<% end %>
		<% if configured_links.include?(:related) %>
      <% solr_url_hash(document, exclude: {'usage' => "primary display"}).each do |location| %>
        <li><%= link_to("<span class=\"glyphicon glyphicon-paperclip\"></span> #{location.fetch('displayLabel',"Related Web Content")}", location['url']) %></li>
      <% end %>
		<% end %>
		<% if configured_links.include?(:mods) %>
			<li><%= link_to '<span class="glyphicon glyphicon-file"></span> Display XML Metadata'.html_safe, item_mods_path(:pid => @document.id),
			{
				:'data-display-url' => item_mods_path(:pid => @document.id, :type => 'formatted_text'),
				:'data-download-url' => item_mods_path(:pid => @document.id, :type => 'download'),
				:onclick => 'return DCV.ModsDownloadModal.show($(this).attr("data-display-url"), $(this).attr("data-download-url"));'
			}
			%></li>
		<% end %>
	</ul>
</div>

app/views/catalog/_search_form.html.erb
  <%= form_tag search_action_url, method: :get, class: ['d-flex','flex-md-row-reverse','flex-sm-column','w-100'] do %>
    <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8, :format)) %>

    <div class="input-group flex-sm-row flex-md-fill">
      <% unless search_fields.empty? %>
        <span class="input-group-prepend">
          <%= hidden_field_tag(:search_field, h(params[:search_field] || search_fields.first[1]), :title => t('blacklight.search.form.search_field.title')) %>
        </span>
      <% end %>
      <%= text_field_tag :q, params[:q], :placeholder => (!query_has_constraints? ?  t(:"dlc.search_placeholder.new.#{controller.controller_name}", default: :'dlc.search_placeholder.new.default').html_safe : t(:"dlc.search_placeholder.modified.#{controller.controller_name}", default: :'dlc.search_placeholder.modifed.default').html_safe), :class => "search_q q form-control", :id => "q", aria: { label: t('blacklight.search.form.search.label')} %>
      <div class="input-group-append">
        <%= link_to '<i class="fa fa-remove"></i>'.html_safe, start_over_path, :title => 'Start Over', :class => 'btn btn-secondary reset-btn' if query_has_constraints? %>
        <button class="btn btn-primary search-btn" type="submit" aria-label="Submit">
          <span class="hidden-xs"><%= (current_page?(root_url)? t('blacklight.search.form.submit') : '') %></span>
          <span class="fa fa-search"></span>
        </button>
      </div>
    </div>

  <% end %>

app/views/catalog/_secondary_nav.html.erb
<nav id="secondary-nav" class="navbar d-flex px-0">
	<ul class="nav nav-pills mr-auto">
		<li class="nav-item">
			<a href="<%=root_path%>" class="nav-link" aria-label="Home"><i class="fa fa-home" aria-hidden="true"></i><span class="d-sm-none pl-1">Home</span></a>
		</li>
		<li class="nav-item">
			<a href="<%=about_path%>" class="nav-link" aria-label="About"><i class="fa fa-info-circle" aria-hidden="true"></i><span class="d-sm-none pl-1">About</span></a>
		</li>
		<li class="dropdown">
			<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
			<ul class="dropdown-menu list-unstyled dropdown-menu-left">
				<li><a href="<%= browse_path('names')%>" class="dropdown-item">Associated Names</a></li>
				<li><a href="<%= browse_path('formats')%>" class="dropdown-item">Formats</a></li>
				<li><a href="<%= browse_path('libraries')%>" class="dropdown-item">Library Locations</a></li>
			</ul>
		</li>
	</ul>
	<ul class="nav nav-pills">
		<li class="nav-item"><a onclick="window.open(this.href);return false;" data-toggle="tooltip" data-placement="bottom" href="https://resolver.library.columbia.edu/lweb0164" title="See All Digital Collections" class="nav-link">All Collections <i class="fa fa-external-link"></i></a></li>
	<%- if params[:action] == 'home' && @subsite.persistent_url -%>
		<li class="nav-item"><button data-copy="<%= @subsite.persistent_url %>" title="Click to copy to clipboard" class="btn btn-secondary nav-link mx-auto" onclick="clipboardFromElement(this);"><span class="fa fa-copy"></span> Copy Link</button></li>
	<%- elsif @document&.has_persistent_url? -%>
		<li class="nav-item"><button data-copy="<%= @document.persistent_url %>" title="Click to copy to clipboard" class="btn btn-secondary nav-link mx-auto" onclick="clipboardFromElement(this);"><span class="fa fa-copy"></span> Copy Link</button></li>
	<%- end -%>
	</ul>
</nav>

app/views/catalog/home-hide.html.erb
<%
featured_proj = controller.digital_projects.select { |proj| proj[:facet_value].present? }.sample
%>

<div class="row">
  <div id="sidebar" class="col-md-3">
    <div class="inner">
       <div id="home-sidebar-news">
          <h6>WELCOME</h6>
            <p>The Digital Library Collections (DLC) website is a gateway to digital reproductions and descriptions of photographs, posters, drawings, objects, ephemera, and manuscripts as well as other archival material from Columbia's rare and special collections.  The DLC repository includes more than <%= rounded_down_and_formatted_dcv_asset_count %> files comprising over <%= rounded_down_and_formatted_dcv_item_count %> unique items, a portion of which are restricted to onsite viewing in the Libraries. <a href="<%= about_url %>">More &raquo;</a></p>
            <hr>
          <%- if featured_proj.present? %>
          <h6>COLLECTION SPOTLIGHT</h6>
          <div class="collection-title"><%= featured_proj[:name] %></div>
		  <p><a href="<%= search_action_path(:f => {'lib_project_short_ssim' => [featured_proj[:facet_value]]})  %>"><img src="<%= featured_proj[:image] %>" class="thumbnail pull-right" alt="<%= featured_proj[:name] %>"></a><%= (featured_proj[:description] || '').html_safe %> <a href="<%= search_action_path(:f => {'lib_project_short_ssim' => [featured_proj[:facet_value]]})  %>" class="inline-block">View this Collection &raquo;</a></p>
          <%- end %>
          <div class="clearfix"></div>
         </div>
      </div>
      <div id="home-sidebar-about">
          <p><a href="<%= about_url %>">Learn more about the DLC &raquo;</a></p>
      </div>
  </div>

  <div id="content" class="col-md-9">
        <div id="home-page-content">

            <div id="home-page-tabs" class="inner">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#projects" data-toggle="tab">Searchable Collections</a></li>
                    <% @browse_lists&.each do |facet_name, data| %>
                        <li><a href="#tab_<%= facet_name %>" data-toggle="tab"><%= data['display_label'] %></a></li>
                    <% end %>
										<li class="pull-right non-tab"><a onclick="window.open(this.href);return false;" data-toggle="tooltip" data-placement="top" href="https://library.columbia.edu/resolve/lweb0164" title="See All Digital Collections">All Collections <i class="glyphicon glyphicon-new-window"></i></a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                    <div class="tab-pane fadein active" id="projects">
                      <%- cache [controller_name, 'projects', 'page', true], expires_in: 2.minutes do -%>
                        <%= render template: 'pages/projects_and_exhibitions' %>
                      <% end %>
                    </div>
                    <% @browse_lists&.each do |facet_name, data| %>
                      <%- cache [controller_name, facet_name, 'page', false], expires_in: 2.minutes do -%>
                        <%= render template: "pages/#{facet_name}", locals: {facet_name: facet_name, data: data} %>
                      <% end %>
                    <% end %>
                </div>
            </div> <!--/.inner-->
        </div>
  </div>

</div>